@startuml
    node "Webserver" {
        HTTPS - [Frontend]
    }

    node "Application Gateway" {
        () "routing" as api_z 
        [Zuul 2] as sz
        api_z - sz
        [Eureka] as eu
        () "api" as dis
        eu - dis
    }

    node "Customer" {
        () "api" as api_c
        api_c - [Microservice Customer]
    }

   
    node "Order" {
        () "api" as api_o
        api_o - [Microservice Order]
    }

   
    node "Stock" {
        () "api" as api_s
        api_s - [Microservice Stock]
    }

    [Frontend] <--> api_z 
    sz <--> [api_c]
    sz <--> [api_o]
    sz <--> [api_s]
   @enduml
