@startuml
    package "DockerImages" {
        class JavaBase 
        class Monitored
        class Production
        class Develop

        JavaBase <|-- Monitored
        Monitored <|-- Production
        Monitored <|-- Develop
    }
@enduml